export const coreValues = [
	{
		section: "Lifestyle",
		values: [
			"Active",
			"Adventure",
			"Challenges",
			"Change and Variety",
			"Freedom",
			"Independence",
			"Privacy",
			"Pleasure",
			"Serenity",
			"Stability",
			"Tranquility",
		],
	},
	{
		section: "Personal Growth",
		values: [
			"Achievement",
			"Advancement",
			"Creativity",
			"Expertise",
			"Fame",
			"Knowledge",
			"Intellectual",
			"Personal Development",
			"Passion",
			"Open-minded",
			"Responsibility",
			"Reputation",
			"Self-Respect",
			"Wisdom",
		],
	},
	{
		section: "Relationships",
		values: [
			"Affection",
			"Close Relationships",
			"Friendships",
			"Having a family",
			"Helping others",
			"Honesty",
			"Loyalty",
			"Quality Relationships",
			"Recognition",
			"Security",
		],
	},
	{
		section: "Purpose",
		values: [
			"Arts",
			"Community",
			"Ecological Awareness",
			"Helping Society",
			"Integrity",
			"Meaningful Work",
			"Merit",
			"Positive Influence",
			"Public Service",
		],
	},
	{
		section: "Societal",
		values: [
			"Accountability",
			"Competence",
			"Competition",
			"Cooperation",
			"Country",
			"Democracy",
			"Economic Security",
			"Effectiveness",
			"Efficiency",
			"Equal Rights",
			"Ethical Practices",
			"Excellence",
			"Leadership",
			"Power and Authority",
			"Money",
			"Wealth",
			"Religion",
			"Women's Rights",
			"Work Under Pressure",
			"Work With Others",
			"Working Alone",
		],
	},
];
